# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaitamaCycleRent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaitamaCycleRent
  pod 'INSPersistentContainer'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'Gloss'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'SaitamaCycleRentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
